# Auto-label PRs based on changed files.
# See https://github.com/actions/labeler

dependencies:
  - changed-files:
      - any-glob-to-any-file:
          - package.json
          - yarn.lock

codegen:
  - changed-files:
      - any-glob-to-any-file:
          - "**/generated/**"
          - "**/openapi*.{yaml,yml,json}"
          - src/**/wso-api-client/**
