parser: babel-eslint
env:
  browser: true
  es6: true
  jest: true
  node: true
  serviceworker: true
extends:
  - eslint:recommended
  - airbnb
  - prettier
  - prettier/react
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
  - jest
  - prettier
  - react-hooks
rules:
  react/forbid-prop-types:
    - warn
    - forbid:
        - any
        - array
  no-restricted-syntax:
    - off
  react/destructuring-assignment:
    - off
  import/no-extraneous-dependencies:
    - error
    - devDependencies: true
  prefer-destructuring:
    - error
    - array: false
  no-continue:
    - off
  import/order:
    - off
  react/jsx-filename-extension:
    - off
  jsx-a11y/anchor-is-valid:
    - off
  jsx-a11y/no-autofocus:
    - off
  react/jsx-one-expression-per-line:
    - off
  react-hooks/exhaustive-deps:
    - off
  react/jsx-props-no-spreading:
    - error
    - html: "ignore"
  no-use-before-define:
    - error
    - functions: false
