trailingComma: "es5"
tabWidth: 2
semi: true
singleQuote: false
printWidth: 80
bracketSpacing: true
jsxBracketSameLine: false
useTabs: false
arrowParens: "always"
jsxSingleQuote: false
htmlWhitespaceSensitivity: "css"
endOfLine: "auto"
quoteProps: "as-needed"
