// Course Reducer
export const COURSE_ADD = "COURSE_ADD";
export const COURSE_REMOVE = "COURSE_REMOVE";
export const COURSE_HIDE = "COURSE_HIDE";
export const COURSE_UNHIDE = "COURSE_UNHIDE";
export const SUBMENU_CHANGE = "SUBMENU_CHANGE";
export const LOAD_COURSES = "LOAD_COURSES";
export const LOAD_CATALOG = "LOAD_CATALOG";
export const RESET_LOAD = "RESET_LOAD";
export const SEARCH_COURSE = "SEARCH_COURSE";
export const TOGGLE_SEM = "TOGGLE_SEM";
export const TOGGLE_DIST = "TOGGLE_DIST";
export const TOGGLE_DIV = "TOGGLE_DIV";
export const TOGGLE_OTHERS = "TOGGLE_OTHERS";
export const TOGGLE_REMOTE = "TOGGLE_REMOTE";
export const TOGGLE_CONFLICT = "TOGGLE_CONFLICT";
export const TOGGLE_LEVEL = "TOGGLE_LEVEL";
export const UPDATE_GAPI = "UPDATE_GAPI";
export const UPDATE_START = "UPDATE_START";
export const UPDATE_END = "UPDATE_END";
export const ADD_NOTIF = "ADD_NOTIF";
export const REMOVE_NOTIF = "REMOVE_NOTIF";
export const SUCCESS = "SUCCESS";
export const WARNING = "WARNING";
export const FAILURE = "FAILURE";
export const CHANGE_SEMESTER = "CHANGE_SEMESTER";
export const CHANGE_TIME_FORMAT = "CHANGE_TIME_FORMAT";
export const CHANGE_ORIENTATION = "CHANGE_ORIENTATION";
export const RESET_FILTERS = "RESET_FILTERS";
export const REMOVE_SEMESTER_COURSES = "REMOVE_SEMESTER_COURSES";
export const TOGGLE_TYPE = "TOGGLE_TYPE";
export const UPDATE_STATE = "UPDATE_STATE";

// Factrak Filters
export const TOGGLE_FACTRAK_SCORE_DISPLAY = "TOGGLE_FACTRAK_SCORE_DISPLAY";
export const TOGGLE_INCLUDE_FACTRAK_NO_SCORES =
  "TOGGLE_INCLUDE_FACTRAK_NO_SCORES";
export const SET_MIN_FACTRAK_SCORE = "SET_MIN_FACTRAK_SCORE";

// Auth Reducer: See authSlice

// Util Reducer: removed because not used

// Goodrich Reducer
export const GOODRICH_ORDER_UPDATE = "GOODRICH_ORDER_UPDATE";
export const GOODRICH_UPDATE_MANAGER_ORDERS = "GOODRICH_UPDATE_MANAGER_ORDERS";
export const GOODRICH_ORDER_LEASE_UPDATE = "GOODRICH_ORDER_LEASE_UPDATE";
