name: CI/CD Build Checker
on:
  push:
    branches:
      - '**' # matches every branch
      - '!production' # excludes production (handled by Jenkins for deployment)
  pull_request:
env:
  NODE_VERSION: '20'

jobs:
  lint:
    name: Syntax & Format Linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Uses Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'yarn'
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Test Build
        run: yarn run build
      - name: Test
        run: yarn run test:ci
      - name: Check errors with ESLint
        run: yarn run lint
      - name: Check format with Prettier
        run: yarn run format:check
