name: Bundle size
on:
  pull_request:
    branches:
      - master
permissions:
  contents: read
  pull-requests: write
env:
  NODE_VERSION: '20'

jobs:
  size:
    name: size-limit
    runs-on: ubuntu-latest
    env:
      CI_JOB_NUMBER: 1
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Uses Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: yarn
      - uses: andresz1/size-limit-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          package_manager: yarn
